name:                melo
version:             0.1.0.0
github:              "chrismanning/melo"
license:             BSD3
author:              "Chris Manning"
maintainer:          "cmanning999@gmail.com"
copyright:           "2019 Chris Manning"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/chrismanning/melo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - melo-format
  - aeson
  - aeson-casing
  - attoparsec
  - authenticate-oauth
  - barbies
  - basement
  - beam-core
  - beam-postgres
  - binary
  - binary-bits
  - bytestring
  - cache
  - clock
  - conduit
  - conduit-audio
  - conduit-audio-lame
  - conduit-audio-samplerate
  - conduit-audio-sndfile
  - containers
  - control-bool
  - country
  - cue-sheet
  - data-default
  - directory
  - directory-tree
  - exceptions
  - filepath
  - fused-effects
  - generic-aeson
  - generic-lens
  - graphql
  - hashable
  - hashtables
  - haxl
  - higgledy
  - http-client
  - http-client-tls
  - http-types
  - lens
  - log-warper
  - monad-control
  - monad-logger
  - mtl
  - network-uri
  - network-uri-json
  - newtype-generics
  - path
  - path-io
  - polysemy
  - polysemy-plugin
  - postgresql-simple
  - range
  - resource-pool
  - safe-exceptions
  - servant-server
  - singletons
  - stm
  - string-combinators
  - tagged
  - template-haskell
  - text
  - text-icu
  - time
  - token-limiter
  - transformers
  - transformers-base
  - unordered-containers
  - uuid
  - vector
  - wai
  - wai-extra
  - warp
  - wreq

executables:
  melo-import:
    source-dirs: app/import
    main: Main.hs
    dependencies:
    - melo
    - melo-format
    - beam-core
    - beam-postgres
    - optparse-applicative
    - postgresql-simple
    - resource-pool
    - text
    - time
  bandcamp-dl:
    source-dirs: app/bandcamp-dl
    main: Main.hs
    dependencies:
      - attoparsec
      - barbies
      - bytestring
      - directory
      - filepath
      - harg
      - higgledy
      - http-client
      - http-types
      - hweblib
      - lens
      - wreq
      - zip

tests:
  melo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melo
    - melo-format
    - aeson
    - attoparsec
    - base16-bytestring
    - beam-core
    - beam-postgres
    - binary
    - bytestring
    - conduit
    - containers
    - fused-effects
    - generic-lens
    - graphql
    - haxl
    - hspec
    - hspec-expectations-lifted
    - lens
    - mtl
    - postgresql-simple
    - raw-strings-qq
    - resource-pool
    - template-haskell
    - temporary
    - text
    - unordered-containers
    - vector
    - wreq

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wnoncanonical-monad-instances

default-extensions:
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- ViewPatterns
