name:                melo
version:             0.1.0.0
github:              "chrismanning/melo"
license:             BSD3
author:              "Chris Manning"
maintainer:          "cmanning999@gmail.com"
copyright:           "2019 Chris Manning"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/chrismanning/melo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - melo-format
  - aeson
  - attoparsec
  - beam-core
  - beam-migrate
  - beam-postgres
  - binary
  - binary-bits
  - bytestring
  - conduit
  - containers
  - country
  - data-default
  - directory
  - filepath
  - generic-aeson
  - generic-lens
  - lens
  - network-uri
  - network-uri-json
  - polysemy
  - postgresql-simple
  - resource-pool
  - servant-server
  - string-combinators
  - text
  - text-icu
  - time
  - uuid
  - wai
  - wai-extra
  - warp

executables:
  melo-import:
    source-dirs: app/import
    main: Main.hs
    dependencies:
    - melo
    - melo-format
    - optparse-applicative
    - text
    - time

tests:
  melo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melo
    - melo-format
    - attoparsec
    - base16-bytestring
    - beam-core
    - beam-migrate
    - beam-postgres
    - binary
    - bytestring
    - conduit
    - generic-lens
    - hspec
    - hspec-expectations-lifted
    - lens
    - postgresql-simple
    - raw-strings-qq
    - temporary
    - text
    - vector

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wnoncanonical-monad-instances

default-extensions:
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DuplicateRecordFields
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- ViewPatterns
