name:                melo
version:             0.1.0.0
github:              "chrismanning/melo"
license:             AGPL-3.0-only
author:              "Chris Manning"
maintainer:          "cmanning999@gmail.com"
copyright:           "2021 Chris Manning"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/chrismanning/melo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - melo-format
  - aeson
  - aeson-casing
  - attoparsec
  - authenticate-oauth
  - barbies
  - binary
  - binary-parser
  - bytestring
  - cache
  - caerbannog
  - clock
  - concurrency
  - conduit
  - conduit-audio
  - conduit-audio-mpg123
  - conduit-audio-sndfile
  - containers
  - control-bool
  - country
  - cue-sheet
  - data-default
  - dependent-map
  - dependent-sum
  - deriving-trans
  - directory
  - directory-tree
  - dns
  - either
  - exceptions
  - extra
  - filepath
  - foldl
  - fsnotify
  - generic-aeson
  - generic-deriving
  - generic-lens
  - hashable
  - hashtables
  - hasql
  - hasql-streams-streaming
  - hasql-transaction
  - hasql-transaction-io
  - hsndfile
  - http-client
  - http-client-tls
  - http-types
  - iproute
  - katip
  - lens
  - lifted-base
  - megaparsec
  - memory
  - monad-control
  - monad-logger
  - morpheus-graphql
  - morpheus-graphql-app
  - morpheus-graphql-core
  - morpheus-graphql-server
  - morpheus-graphql-subscriptions
  - mtl
  - multistate
  - natural-sort
  - network
  - network-bsd
  - network-multicast
  - network-uri
  - network-uri-json
  - newtype-generics
  - opaleye
  - path
  - path-io
  - postgresql-binary
  - product-profunctors
  - profunctors
  - random
  - range
  - rel8
  - resource-pool
  - resourcet
  - safe-exceptions
  - scotty
  - servant
  - servant-server
  - singletons
  - stm
  - streaming
  - string-combinators
  - tagged
  - template-haskell
  - text
#  - text-icu
  - time
  - token-limiter
  - transformers
  - transformers-base
  - unordered-containers
  - utf8-string
  - uuid
  - vector
  - wai
  - wai-cors
  - wai-extra
  - wai-websockets
  - warp
  - wave
  - websockets
  - witch
  - wreq

executables:
  melo-api:
    source-dirs: app/api
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - melo
  melo-player:
    source-dirs: app/player
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - melo
      - conduit-audio
      - conduit-audio-sndfile
      - conduit-audio-mpg123

tests:
  melo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melo
    - melo-format
    - aeson
    - aeson-casing
    - attoparsec
    - base16-bytestring
    - binary
    - bytestring
    - concurrency
    - conduit
    - containers
    - generic-lens
    - hashable
    - hspec
    - hspec-expectations-lifted
    - lens
    - monad-control
    - monad-mock
    - mtl
    - raw-strings-qq
    - rel8
    - resource-pool
    - safe-exceptions
    - template-haskell
    - temporary
    - text
    - transformers
    - transformers-base
    - unordered-containers
    - uuid
    - vector
    - witch
    - wreq

ghc-options:
- -O0
- -Wall
- -Wcompat
- -fno-warn-name-shadowing
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wnoncanonical-monad-instances
- -fwrite-ide-info
- -hiedir=.hie

default-extensions:
- GHC2021
- ApplicativeDo
- BlockArguments
- DataKinds
- DefaultSignatures
- DerivingStrategies
- DerivingVia
- DisambiguateRecordFields
- DuplicateRecordFields
- FunctionalDependencies
- GADTs
- ImpredicativeTypes
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
#- OverloadedRecordUpdate
- OverloadedStrings
- PatternSynonyms
#- RebindableSyntax
- RecordWildCards
- StrictData
- TemplateHaskell
- TypeFamilies
- TypeFamilyDependencies
- ViewPatterns
