name:                melo
version:             0.1.0.0
github:              "chrismanning/melo"
license:             AGPL-3.0-only
author:              "Chris Manning"
maintainer:          "cmanning999@gmail.com"
copyright:           "2021 Chris Manning"

language: GHC2021

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/chrismanning/melo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  other-modules:
  - Prelude
  dependencies:
  - melo-format
  - abstract-par
  - aeson
  - aeson-casing
  - ansi-terminal
  - async
  - attoparsec
  - authenticate-oauth
  - barbies
  - binary
  - binary-parser
  - bytestring
  - bytestring-trie
  - cache
  - caerbannog
  - casing
  - clock
  - co-log-core
  - concurrency
  - conduit
  - conduit-audio
  - conduit-audio-mpg123
  - conduit-audio-sndfile
  - containers
  - control-bool
  - country
  - cue-sheet
  - data-default
  - deepseq
  - dependent-map
  - dependent-sum
  - deriving-aeson
  - deriving-trans
  - directory
  - directory-tree
  - dns
  - dotenv
  - edit-distance
  - either
  - exceptions
  - extra
  - filepath
  - foldl
  - fsnotify
  - generic-deriving
  - generic-lens
  - hashable
  - hashtables
  - hasql
  - hasql-streams-streaming
  - hasql-transaction
  - hasql-transaction-io
  - hs-opentelemetry-api
  - hs-opentelemetry-exporter-otlp
  - hs-opentelemetry-instrumentation-conduit
  - hs-opentelemetry-instrumentation-http-client
  - hs-opentelemetry-instrumentation-wai
  - hs-opentelemetry-sdk
  - hs-opentelemetry-utils-exceptions
  - hsndfile
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - imagesize-conduit
  - io-classes
  - iproute
  - katip
  - katip-wai
  - lens
  - lifted-base
  - megaparsec
  - memory
  - monad-control
  - monad-logger
  - monad-loops
  - monad-par
  - monad-par-extras
  - morpheus-graphql
  - morpheus-graphql-app
  - morpheus-graphql-core
  - morpheus-graphql-server
  - morpheus-graphql-subscriptions
  - mtl
  - natural-sort
  - network
  - network-bsd
  - network-multicast
  - network-uri
  - network-uri-json
  - newtype-generics
  - opaleye
  - opentelemetry
  - path
  - path-io
  - postgresql-binary
  - primitive
  - product-profunctors
  - profunctors
  - random
  - range
  - rel8
  - resource-pool
  - resourcet
  - rsocket
  - rsocket-transport-tcp
  - safe-exceptions
  - scotty
  - servant
  - servant-server
  - singletons
  - stm
  - streaming
  - streaming-bytestring
  - streaming-utils
  - strict-stm
  - string-combinators
  - tagged
  - template-haskell
  - text
#  - text-icu
  - text-show
  - text-show-instances
  - time
  - token-limiter
  - transformers
  - transformers-base
  - ttrie
  - typerep-map
  - unagi-chan
  - unliftio
  - unordered-containers
  - utf8-string
  - uuid
  - vector
  - vector-algorithms
  - wai
  - wai-cors
  - wai-extra
  - wai-websockets
  - warp
  - wave
  - websockets
  - witch
  - witherable

executables:
  melo-api:
    source-dirs: app/api
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - melo

tests:
  melo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melo
    - melo-format
    - aeson
    - aeson-casing
    - attoparsec
    - base16-bytestring
    - binary
    - bytestring
    - concurrency
    - conduit
    - containers
    - either
    - generic-lens
    - hashable
    - hspec
    - hspec-expectations-lifted
    - lens
    - monad-control
    - monad-mock
    - mtl
    - raw-strings-qq
    - rel8
    - resource-pool
    - safe-exceptions
    - template-haskell
    - temporary
    - text
    - time
    - transformers
    - transformers-base
    - unordered-containers
    - uuid
    - vector
    - witch

ghc-options:
- -O0
- -debug
- -Wall
- -Wcompat
- -Wno-name-shadowing
- -Wno-missing-home-modules
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wnoncanonical-monad-instances
- -Werror=incomplete-patterns
- -Werror=missing-methods
- -fwrite-ide-info
- -hiedir=.hie

default-extensions:
- ApplicativeDo
- BlockArguments
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DisambiguateRecordFields
- DuplicateRecordFields
- FunctionalDependencies
- GADTs
- ImpredicativeTypes
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
#- OverloadedRecordUpdate
- OverloadedStrings
- PatternSynonyms
#- RebindableSyntax
- RecordWildCards
- StrictData
- TemplateHaskell
- TypeFamilies
- TypeFamilyDependencies
- ViewPatterns
