resolver: nightly-2023-12-01

packages:
- melo-format
- .

extra-deps:
  - github: chrismanning/binary-bits
    commit: 8d9ffaa0e705a04f231d5ce46271f7713ef0f7dc
  - github: chrismanning/hfsnotify
    commit: f5a79a5a4a0e8f429dabb83ed6e713743d317ed5
  - github: mtolly/conduit-audio
    commit: a374e66f018ed75e553e9ba076ee3227560db343
    subdirs:
      - conduit-audio
      - conduit-audio-lame
      - conduit-audio-mpg123
      - conduit-audio-samplerate
      - conduit-audio-sndfile
  - github: factisresearch/text-icu
    commit: d8c8bbd7754c38ff99f548a53d0881120b284972
  - github: chrismanning/monad-mock
    commit: b85d79677065f31c9c448814cccd282d5ecfbe53
  - github: chrismanning/cue-sheet
    commit: fc6d7c15bdee3ae7877e2e6eb2d49abb154383f6
  - github: chrismanning/rel8
    commit: dd7eeff9e1e3519342a8229ab48038d6840a6b85
  - github: chrismanning/kqueue
    commit: 742c7a29b5c5e43b330667f259b7ccea4503ba98
  - github: nikita-volkov/postgresql-binary
    commit: 9733ac2a9f4a1b2f172e8f088de8414e4a61ef2c
  - github: andremarianiello/hasql-transaction-io
    commit: e5a289f2a3283e620a571dc0b2c15d7b5983a54c
  - github: haskell-streaming/streaming
    commit: 0c815bf9043d0f0cbda92b80ef791892e2b7fb43
  - github: chrismanning/monad-par
    commit: a679fa5c9d3440ea831e58f916ba5afec1375612
    subdirs:
      - abstract-par
      - monad-par
      - monad-par-extras
  - github: chrismanning/hs-opentelemetry
    commit: b0f546ae6aebe9ec483b107c5d43db875234be7b
    subdirs:
      - api
      - exporters/otlp
      - instrumentation/conduit
      - instrumentation/http-client
      - instrumentation/hspec
      - instrumentation/wai
      - otlp
      - propagators/b3
      - propagators/w3c
      - sdk
      - utils/exceptions
  - git: git@github.com:chrismanning/rsocket-hs.git
    commit: ce25103b836ae95e1c479bc12e004ecab40e0c58
    subdirs:
      - rsocket
      - rsocket-transport-tcp
  - hasql-streams-core-0.1.0.0
  - hasql-streams-streaming-0.1.0.0
  - mpg123-bindings-0.1.0.0
  - network-uri-json-0.3.1.1
  - streaming-binary-0.3.0.1
  - token-limiter-0.2.0.3
  - streaming-utils-0.2.4.0
  - streaming-bytestring-0.3.0
  - morpheus-graphql-0.27.3
  - morpheus-graphql-app-0.27.3
  - morpheus-graphql-client-0.27.3
  - morpheus-graphql-code-gen-0.27.3
  - morpheus-graphql-code-gen-utils-0.27.3
  - morpheus-graphql-core-0.27.3
  - morpheus-graphql-server-0.27.3
  - morpheus-graphql-subscriptions-0.27.3
  - country-0.2.3.1
  - cache-0.1.3.0
  - relude-1.2.0.0
  - bytebuild-0.3.13.0
  - zigzag-0.0.1.0
  - thread-utils-context-0.3.0.3
  - thread-utils-finalizers-0.1.1.0
  - typerep-map-0.6.0.0
  - io-classes-1.2.0.0
  - io-classes-mtl-0.1.0.2
  - io-sim-1.2.0.0
  - si-timers-1.2.0.0
  - strict-stm-1.2.0.0

allow-newer: true
