name:                melo-format
version:             0.1.0.0
github:              "chrismanning/melo"
license:             BSD3
author:              "Chris Manning"
maintainer:          "cmanning999@gmail.com"
copyright:           "2021 Chris Manning"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/chrismanning/melo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - array
    - binary
    - bytestring
    # binary-bits fork
    - caerbannog
    - containers
    - data-default
    - directory
    - extra
    - filepath
    - generic-lens
    - hashable
    - microlens
    - microlens-th
    - pureMD5
    - range
    - safe-exceptions
    - split
    - text
    - time
    - unordered-containers
    - vector

#executables:
#  melo-detect:
#    source-dirs: app/detect
#    main: Main.hs
#    dependencies:
#      - melo-format
#      - extra
#      - generic-lens
#      - microlens
#      - optparse-applicative
#      - text
#      - time
#      - unordered-containers

tests:
  melo-format-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - melo-format
    - base16-bytestring
    - binary
    - bytestring
    - conduit
    - directory
    - filepath
    - hspec
    - hspec-expectations-lifted
    - microlens
    - safe-exceptions
    - temporary
    - text
    - unordered-containers
    - vector

ghc-options:
  - -O2
  - -Wall
  - -Wcompat
  - -fno-warn-name-shadowing
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wnoncanonical-monad-instances
  - -fwrite-ide-info
  - -hiedir=../.hie

default-extensions:
  - GHC2021
  - ApplicativeDo
  - DataKinds
  - DefaultSignatures
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  - OverloadedLabels
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - RecordWildCards
  - TemplateHaskell
  - TypeFamilies
  - TypeFamilyDependencies
  - ViewPatterns
